// Generated by CoffeeScript 1.11.1
(function() {
  var CreateCertificateRequest, CreateEERequest, ReissueCertificateRequest, RenewCertificateRequest,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CreateCertificateRequest = (function() {
    function CreateCertificateRequest(product, years, csr, dcvType) {
      this.product = product;
      this.years = years;
      this.csr = csr;
      this.dcvType = dcvType;
      this.toArray = bind(this.toArray, this);
      this.subjectAlternativeNames = [];
      this.dcv = [];
      this.company = '';
      this.department = '';
      this.address = '';
      this.zipcode = '';
      this.city = '';
      this.approverFirstName = '';
      this.approverLastName = '';
      this.approverEmail = '';
      this.approverPhone = '';
      this.kvk = '';
      this.reference = '';
      this.language = '';
    }

    CreateCertificateRequest.prototype.toArray = function() {
      var result;
      result = {
        product: this.product,
        years: this.years,
        csr: this.csr,
        dcvType: this.dcvType
      };
      if (this.subjectAlternativeNames.length > 0) {
        result['subjectAlternativeNames'] = this.subjectAlternativeNames.join(',');
      }
      if (this.dcv.length > 0) {
        result['dcv'] = JSON.stringify(this.dcv);
      }
      if (this.company !== '') {
        result['company'] = this.company;
      }
      if (this.department !== '') {
        result['department'] = this.department;
      }
      if (this.address !== '') {
        result['address'] = this.address;
      }
      if (this.zipcode !== '') {
        result['zipcode'] = this.zipcode;
      }
      if (this.city !== '') {
        result['city'] = this.city;
      }
      if (this.approverFirstName !== '') {
        result['approverFirstName'] = this.approverFirstName;
      }
      if (this.approverLastName !== '') {
        result['approverLastName'] = this.approverLastName;
      }
      if (this.approverEmail !== '') {
        result['approverEmail'] = this.approverEmail;
      }
      if (this.approverPhone !== '') {
        result['approverPhone'] = this.approverPhone;
      }
      if (this.kvk !== '') {
        result['kvk'] = this.kvk;
      }
      if (this.reference !== '') {
        result['reference'] = this.reference;
      }
      if (this.language !== '') {
        result['language'] = this.language;
      }
      return result;
    };

    return CreateCertificateRequest;

  })();

  CreateEERequest = (function() {
    function CreateEERequest() {
      this.toArray = bind(this.toArray, this);
      this.csr = '';
      this.subjectAlternativeNames = [];
      this.approverFirstName = '';
      this.approverLastName = '';
      this.approverEmail = '';
      this.approverPhone = '';
      this.dcvType = 'FILE';
      this.validate = false;
    }

    CreateEERequest.prototype.toArray = function() {
      var result;
      result = {};
      if (this.subjectAlternativeNames.length > 0) {
        result['subjectAlternativeNames'] = this.subjectAlternativeNames.join(',');
      }
      result = {
        csr: this.csr,
        approverFirstName: this.approverFirstName,
        approverLastName: this.approverLastName,
        approverEmail: this.approverEmail,
        approverPhone: this.approverPhone,
        dcvType: this.dcvType,
        validate: this.validate ? 1 : 0
      };
      return result;
    };

    return CreateEERequest;

  })();

  ReissueCertificateRequest = (function() {
    function ReissueCertificateRequest(csr, dcvType) {
      this.csr = csr;
      this.dcvType = dcvType;
      this.toArray = bind(this.toArray, this);
      this.subjectAlternativeNames = [];
      this.dcv = [];
      this.company = '';
      this.department = '';
      this.address = '';
      this.zipcode = '';
      this.city = '';
      this.approverFirstName = '';
      this.approverLastName = '';
      this.approverEmail = '';
      this.approverPhone = '';
      this.kvk = '';
      this.reference = '';
      this.language = '';
    }

    ReissueCertificateRequest.prototype.toArray = function() {
      var result;
      result = {
        csr: this.csr,
        dcvType: this.dcvType
      };
      if (this.subjectAlternativeNames.length > 0) {
        result['subjectAlternativeNames'] = this.subjectAlternativeNames.join(',');
      }
      if (this.dcv.length > 0) {
        result['dcv'] = JSON.stringify(this.dcv);
      }
      if (this.company !== '') {
        result['company'] = this.company;
      }
      if (this.department !== '') {
        result['department'] = this.department;
      }
      if (this.address !== '') {
        result['address'] = this.address;
      }
      if (this.zipcode !== '') {
        result['zipcode'] = this.zipcode;
      }
      if (this.city !== '') {
        result['city'] = this.city;
      }
      if (this.approverFirstName !== '') {
        result['approverFirstName'] = this.approverFirstName;
      }
      if (this.approverLastName !== '') {
        result['approverLastName'] = this.approverLastName;
      }
      if (this.approverEmail !== '') {
        result['approverEmail'] = this.approverEmail;
      }
      if (this.approverPhone !== '') {
        result['approverPhone'] = this.approverPhone;
      }
      if (this.kvk !== '') {
        result['kvk'] = this.kvk;
      }
      if (this.reference !== '') {
        result['reference'] = this.reference;
      }
      if (this.language !== '') {
        result['language'] = this.language;
      }
      return result;
    };

    return ReissueCertificateRequest;

  })();

  RenewCertificateRequest = (function() {
    function RenewCertificateRequest(product, years, csr, dcvType) {
      this.product = product;
      this.years = years;
      this.csr = csr;
      this.dcvType = dcvType;
      this.toArray = bind(this.toArray, this);
      this.subjectAlternativeNames = [];
      this.dcv = [];
      this.company = '';
      this.department = '';
      this.address = '';
      this.zipcode = '';
      this.city = '';
      this.approverFirstName = '';
      this.approverLastName = '';
      this.approverEmail = '';
      this.approverPhone = '';
      this.kvk = '';
      this.reference = '';
      this.language = '';
    }

    RenewCertificateRequest.prototype.toArray = function() {
      var result;
      result = {
        product: this.product,
        years: this.years,
        csr: this.csr,
        dcvType: this.dcvType
      };
      if (this.subjectAlternativeNames.length > 0) {
        result['subjectAlternativeNames'] = this.subjectAlternativeNames.join(',');
      }
      if (this.dcv.length > 0) {
        result['dcv'] = JSON.stringify(this.dcv);
      }
      if (this.company !== '') {
        result['company'] = this.company;
      }
      if (this.department !== '') {
        result['department'] = this.department;
      }
      if (this.address !== '') {
        result['address'] = this.address;
      }
      if (this.zipcode !== '') {
        result['zipcode'] = this.zipcode;
      }
      if (this.city !== '') {
        result['city'] = this.city;
      }
      if (this.approverFirstName !== '') {
        result['approverFirstName'] = this.approverFirstName;
      }
      if (this.approverLastName !== '') {
        result['approverLastName'] = this.approverLastName;
      }
      if (this.approverEmail !== '') {
        result['approverEmail'] = this.approverEmail;
      }
      if (this.approverPhone !== '') {
        result['approverPhone'] = this.approverPhone;
      }
      if (this.kvk !== '') {
        result['kvk'] = this.kvk;
      }
      if (this.reference !== '') {
        result['reference'] = this.reference;
      }
      if (this.language !== '') {
        result['language'] = this.language;
      }
      return result;
    };

    return RenewCertificateRequest;

  })();

  module.exports = {
    CreateCertificateRequest: CreateCertificateRequest,
    CreateEERequest: CreateEERequest,
    ReissueCertificateRequest: ReissueCertificateRequest,
    RenewCertificateRequest: RenewCertificateRequest
  };

}).call(this);
