// Generated by CoffeeScript 1.10.0
var CreateCertificateRequest, ReissueCertificateRequest, RenewCertificateRequest,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

CreateCertificateRequest = (function() {
  function CreateCertificateRequest(product, years, csr, dcvType) {
    this.product = product;
    this.years = years;
    this.csr = csr;
    this.dcvType = dcvType;
    this.toArray = bind(this.toArray, this);
    this.subjectAlternativeNames = [];
    this.dcv = [];
    this.company = '';
    this.department = '';
    this.address = '';
    this.zipcode = '';
    this.city = '';
    this.approverFirstName = '';
    this.approverLastName = '';
    this.approverEmail = '';
    this.approverPhone = '';
    this.kvk = '';
    this.reference = '';
  }

  CreateCertificateRequest.prototype.toArray = function() {
    var result;
    result = {
      product: this.product,
      years: this.years,
      csr: this.csr,
      dcvType: this.dcvType
    };
    if (this.subjectAlternativeNames.length > 0) {
      result['subjectAlternativeNames'] = this.subjectAlternativeNames.join(',');
    }
    if (this.dcv.length > 0) {
      result['dcv'] = JSON.stringify(this.dcv);
    }
    if (this.company !== '') {
      result['company'] = this.company;
    }
    if (this.department !== '') {
      result['department'] = this.department;
    }
    if (this.address !== '') {
      result['address'] = this.address;
    }
    if (this.zipcode !== '') {
      result['zipcode'] = this.zipcode;
    }
    if (this.city !== '') {
      result['city'] = this.city;
    }
    if (this.approverFirstName !== '') {
      result['approverFirstName'] = this.approverFirstName;
    }
    if (this.approverLastName !== '') {
      result['approverLastName'] = this.approverLastName;
    }
    if (this.approverEmail !== '') {
      result['approverEmail'] = this.approverEmail;
    }
    if (this.approverPhone !== '') {
      result['approverPhone'] = this.approverPhone;
    }
    if (this.kvk !== '') {
      result['kvk'] = this.kvk;
    }
    if (this.reference !== '') {
      result['reference'] = this.reference;
    }
    return result;
  };

  return CreateCertificateRequest;

})();

ReissueCertificateRequest = (function() {
  function ReissueCertificateRequest(csr, dcvType) {
    this.csr = csr;
    this.dcvType = dcvType;
    this.toArray = bind(this.toArray, this);
    this.subjectAlternativeNames = [];
    this.dcv = [];
    this.company = '';
    this.department = '';
    this.address = '';
    this.zipcode = '';
    this.city = '';
    this.approverFirstName = '';
    this.approverLastName = '';
    this.approverEmail = '';
    this.approverPhone = '';
    this.kvk = '';
    this.reference = '';
  }

  ReissueCertificateRequest.prototype.toArray = function() {
    var result;
    result = {
      csr: this.csr,
      dcvType: this.dcvType
    };
    if (this.subjectAlternativeNames.length > 0) {
      result['subjectAlternativeNames'] = this.subjectAlternativeNames.join(',');
    }
    if (this.dcv.length > 0) {
      result['dcv'] = JSON.stringify(this.dcv);
    }
    if (this.company !== '') {
      result['company'] = this.company;
    }
    if (this.department !== '') {
      result['department'] = this.department;
    }
    if (this.address !== '') {
      result['address'] = this.address;
    }
    if (this.zipcode !== '') {
      result['zipcode'] = this.zipcode;
    }
    if (this.city !== '') {
      result['city'] = this.city;
    }
    if (this.approverFirstName !== '') {
      result['approverFirstName'] = this.approverFirstName;
    }
    if (this.approverLastName !== '') {
      result['approverLastName'] = this.approverLastName;
    }
    if (this.approverEmail !== '') {
      result['approverEmail'] = this.approverEmail;
    }
    if (this.approverPhone !== '') {
      result['approverPhone'] = this.approverPhone;
    }
    if (this.kvk !== '') {
      result['kvk'] = this.kvk;
    }
    if (this.reference !== '') {
      result['reference'] = this.reference;
    }
    return result;
  };

  return ReissueCertificateRequest;

})();

RenewCertificateRequest = (function() {
  function RenewCertificateRequest(product, years, csr, dcvType) {
    this.product = product;
    this.years = years;
    this.csr = csr;
    this.dcvType = dcvType;
    this.toArray = bind(this.toArray, this);
    this.subjectAlternativeNames = [];
    this.dcv = [];
    this.company = '';
    this.department = '';
    this.address = '';
    this.zipcode = '';
    this.city = '';
    this.approverFirstName = '';
    this.approverLastName = '';
    this.approverEmail = '';
    this.approverPhone = '';
    this.kvk = '';
    this.reference = '';
  }

  RenewCertificateRequest.prototype.toArray = function() {
    var result;
    result = {
      product: this.product,
      years: this.years,
      csr: this.csr,
      dcvType: this.dcvType
    };
    if (this.subjectAlternativeNames.length > 0) {
      result['subjectAlternativeNames'] = this.subjectAlternativeNames.join(',');
    }
    if (this.dcv.length > 0) {
      result['dcv'] = JSON.stringify(this.dcv);
    }
    if (this.company !== '') {
      result['company'] = this.company;
    }
    if (this.department !== '') {
      result['department'] = this.department;
    }
    if (this.address !== '') {
      result['address'] = this.address;
    }
    if (this.zipcode !== '') {
      result['zipcode'] = this.zipcode;
    }
    if (this.city !== '') {
      result['city'] = this.city;
    }
    if (this.approverFirstName !== '') {
      result['approverFirstName'] = this.approverFirstName;
    }
    if (this.approverLastName !== '') {
      result['approverLastName'] = this.approverLastName;
    }
    if (this.approverEmail !== '') {
      result['approverEmail'] = this.approverEmail;
    }
    if (this.approverPhone !== '') {
      result['approverPhone'] = this.approverPhone;
    }
    if (this.kvk !== '') {
      result['kvk'] = this.kvk;
    }
    if (this.reference !== '') {
      result['reference'] = this.reference;
    }
    return result;
  };

  return RenewCertificateRequest;

})();

module.exports = {
  CreateCertificateRequest: CreateCertificateRequest,
  ReissueCertificateRequest: ReissueCertificateRequest,
  RenewCertificateRequest: RenewCertificateRequest
};
